### ISSUE TITLE
Batched conjugate gradient is brittle

### ISSUE THREAD

**Issue by Xuzzo** [appliedAI-Initiative/pyDVL#137]
I have found several times that the batched cg does not converge while the scipy cg converges. I believe there is something strange going on with the step size. However, even in the cases in which it converges, it is slower than the non-batched one, so for now we can use the scipy implementation and leave this for when we are benchmarking runtime.

**Comment by mdbenito** [comment]
@Xuzzo What is the status here? Have we ditched the unnecessary code? Or is there a (valid) reason to keep it around? If it doesn't include any functionality missing from scipy's implementation, please just delete it.

**Comment by Xuzzo** [comment]
If we include other frameworks (like JAX?) that allow to do a batched second derivative (so a batched calculation of the Hessian) having this should make stuff much faster. This is true conditional on the fact that we fix the problem with the step size. That is why I am more inclined to keep it until we clarify this. At the moment, we return a warning if anyone tries to use batched cg, saying that it has issues and that we discourage its usage.
