### ISSUE TITLE
Properly investigate usefulness of Data Utility Learning

### ISSUE THREAD

**Issue by AnesBenmerzoug** [appliedAI-Initiative/pyDVL#138]
Data Utility Learning was implemented as part of PR #119 but it was only tested on a small dataset of 15 samples.

We should use it on bigger and noisier datasets and investigate whether it is actually useful.

We should also investigate the theoretical bounds derived in the paper ( $(\epsilon, \delta)$-approximation and required number of samples).

**Comment by mdbenito** [comment]
Closing as it is part of #206 .
