### ISSUE TITLE
Loading spotify dataset does not work on CI

### ISSUE THREAD

**Issue by AnesBenmerzoug** [appliedAI-Initiative/pyDVL#147]
Using the [`load_spotify_dataset`](https://github.com/appliedAI-Initiative/pyDVL/blob/develop/src/pydvl/utils/dataset.py#L311) function does not currently work in [CI](https://github.com/appliedAI-Initiative/pyDVL/actions/runs/3204873521/jobs/5236780612#step:8:506).

**Comment by mdbenito** [comment]
Is this still valid? If yes, please add the accepted label

**Comment by mdbenito** [comment]
See e.g. https://github.com/appliedAI-Initiative/pyDVL/actions/runs/3364319485/jobs/5578577582#step:8:1110

**Comment by mdbenito** [comment]
Still valid: https://github.com/appliedAI-Initiative/pyDVL/actions/runs/3364319485/jobs/5578577582#step:8:1110
