### ISSUE TITLE
Ideas for a change of interface to MapReduceJob

### ISSUE THREAD

**Issue by mdbenito** [appliedAI-Initiative/pyDVL#165]
* A job contains all the info it needs to run. Therefore passing arguments to `__call__` doesn't make much sense.
* Instead, all arguments to the map function are passed upon construction and `put()` to the backend inside the constructor, thus hiding this implementation detail from the user of `MapReduceJob` .
* One such argument is necessarily the data to use, so it should not be part of `map_kwargs` but a standalone arg to the constructor of `MapReduceJob`
 
Additionally:
* we avoid duplicating arguments in `__call__` like `chunkify`, etc.
* we undo the typing workaround with `Any`
* `num_workers` in `ParalleConfig` should be renamed to `n_local_workers` with proper explanation of the difference with `n_jobs`

**Comment by mdbenito** [comment]
@AnesBenmerzoug what do you think?

**Comment by AnesBenmerzoug** [comment]
@mdbenito I am currently trying to make these changes. All of them are simple except the one related to passing the utility as a constructor parameter or as a parameter to the `__call__` method instead of in `map_kwargs`. 

I'm having a hard time finding a way to do it without tying `MapReduceJob` to `Utility`.

**Comment by mdbenito** [comment]
I think it is ok to leave the utility in `map_kwargs`. Only the data to operate on is common to any map reduce job, and could be made into a standalone argument of the constructor.

Additionally, we can dispense with the ugly kwargs parameter altogether and pass partially applied functions to `map_func`, which is much cleaner. I would also remove `reduce_kwargs` which seems to be used just once and for a trivial thing and can again be dispensed with by using `functools.partial`
