### ISSUE TITLE
Define and use return types for all Shapley methods

### ISSUE THREAD

**Issue by mdbenito** [appliedAI-Initiative/pyDVL#178]
Instead of returning ordereddicts or tuples, use type aliases, namedtuples and dataclasses.

**Comment by AnesBenmerzoug** [comment]
We could also use a dedicated result class just like Scipy's [OptimizeResult](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.OptimizeResult.html#scipy.optimize.OptimizeResult) or Transformers [ModelOutput](https://huggingface.co/docs/transformers/v4.23.1/en/main_classes/output#transformers.modeling_outputs.BaseModelOutput).
