### ISSUE TITLE
Make package PEP-561 compliant

### ISSUE THREAD

**Issue by AnesBenmerzoug** [appliedAI-Initiative/pyDVL#280]
Current pyDVL is not [PEP-561](https://peps.python.org/pep-0561/) compliant i.e. the package's we distribute do not come with type information.

 In order to make pyDVL's type hints available for users when they use it as an external dependency, we need to simply, as described in PEP-561 and shown [here](https://blog.whtsky.me/tech/2021/dont-forget-py.typed-for-your-typed-python-package/), add a single line to `setup.py`:

```python
setup(
    ...,
   package_data={"pyDVL": ["py.typed"]},
    ...,
)
```

**Comment by mdbenito** [comment]
For the record, mypy requires [an additional option in setup.py](https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages)
