### ISSUE TITLE
Use metaclasses in Influence Functions to check for availability of PyTorch

### ISSUE THREAD

**Issue by AnesBenmerzoug** [appliedAI-Initiative/pyDVL#297]
As discussed during our meeting, we should use metaclasses instead of try except blocks at the top of modules to check if PyTorch is installed.

It can be done as shown in [this article](https://python-3-patterns-idioms-test.readthedocs.io/en/latest/Metaprogramming.html#example-self-registration-of-subclasses).

**Comment by mdbenito** [comment]
Did we think about the type checker complaining if it doesn't know about torch types when torch isn't installed?

**Comment by mdbenito** [comment]
@Xuzzo What's the status here and the relation to #340 ?

**Comment by mdbenito** [comment]
Abstraction to multiple frameworks done in #394
