### ISSUE TITLE
Implement non-blocking postprocessing for MapReduce

### ISSUE THREAD

**Issue by kosmitive** [appliedAI-Initiative/pyDVL#359]
Currently the reduce operator blocks until all map tasks

https://github.com/appliedAI-Initiative/pyDVL/blob/d5381d7a51e26a7e8d904c91ac0f01d67717bb9e/src/pydvl/utils/parallel/map_reduce.py#L182-L187

 are finished, which is implicitly encoded by the used reduce operator

https://github.com/appliedAI-Initiative/pyDVL/blob/d5381d7a51e26a7e8d904c91ac0f01d67717bb9e/src/pydvl/value/semivalues.py#L151

used in the algorithms. This affects not only semi-values but all  other algorithms as well. Optimally we adapt the pattern
 
```python
import time
import random
import ray

ray.init(num_cpus = 4)

@ray.remote
def do_some_work(x):
    time.sleep(random.uniform(0, 4)) # Replace this with work you need to do.
    return x

def process_incremental(sum, result):
    time.sleep(1) # Replace this with some processing code.
    return sum + result

start = time.time()
result_ids = [do_some_work.remote(x) for x in range(4)]
sum = 0
while len(result_ids):
    done_id, result_ids = ray.wait(result_ids)
    sum = process_incremental(sum, ray.get(done_id[0]))
print("duration =", time.time() - start, "\nresult = ", sum)
```

to our use case.

**Comment by mdbenito** [comment]
I'm not sure that "pattern" you mention makes sense. the reduction operation map-reduce has to wait until it's done by definition. If you are interested in an overall progress report, we used to have that before. I'm not sure if and when it disappeared. Also, any behaviour we implement must be independent of the backend.

**Comment by kosmitive** [comment]
Yes, MapReduce requires all maps first to be ready. In the case of a complex reduce operator (which is a combination of binary reductions) it induces a speedup. Anyway today I have spotted we already have this (partly, if I am not mistaken) available for limiting the number of concurrent tasks. So in our case the speed up should be marginal (not sure about additional overhead). And we might need a differentiation for the two reduction operators.
