### ISSUE TITLE
Make dataset support multiple output dimensions.

### ISSUE THREAD

**Issue by kosmitive** [appliedAI-Initiative/pyDVL#36]
Currently the dateset only supports one single dimension for y. In future versions we want y to be multiple dimensional and hence:

- [x] Add multiple dimension to dataset, e.g. throw no exception
- [ ] Extend influence functions to the more general case, see TODO in code.

@Xuzzo How about Shapley version?

**Comment by mdbenito** [comment]
Closing in favour of a dedicated issue
