### ISSUE TITLE
Ray via pip not working for Apple ARM-based CPU

### ISSUE THREAD

**Issue by schroedk** [appliedAI-Initiative/pyDVL#367]
It seems, that in order to use ray with ARM-based Apple CPUs (M1, M2), one has to install a certain dependency of ray via conda package manager

`ImportError while loading conftest '/Users/kristof/Projects/pyDVL/tests/conftest.py'.
tests/conftest.py:9: in <module>
    import ray
.tox/base/lib/python3.10/site-packages/ray/__init__.py:101: in <module>
    _configure_system()
.tox/base/lib/python3.10/site-packages/ray/__init__.py:65: in _configure_system
    raise ImportError(
E   ImportError: Failed to import grpc on Apple Silicon. On Apple Silicon machines, try `pip uninstall grpcio; conda install grpcio`. Check out https://docs.ray.io/en/master/ray-overview/installation.html#m1-mac-apple-silicon-support for more details.
ERROR: InvocationError for command /Users/kristof/Projects/pyDVL/.tox/base/bin/pytest tests/utils -vv --cov .tox/base/lib/python3.10/site-packages/pydvl -m 'not torch' (exited with code 4)`

Installing via conda works (tested on a M2 machine). Should we handle this somehow or put a note in the README?

**Comment by schroedk** [comment]
@mdbenito

**Comment by mdbenito** [comment]
See #380 about that.

**Comment by mdbenito** [comment]
If we merge #408 this is no longer our concern
