### ISSUE TITLE
Add cupy to `extras_requires` 

### ISSUE THREAD

**Issue by mdbenito** [appliedAI-Initiative/pyDVL#368]
We should add a new `extras_requires` for cupy. Maybe "gpu"? There is a nice idea on how to maintain this [here](https://hanxiao.io/2019/11/07/A-Better-Practice-for-Managing-extras-require-Dependencies-in-Python/)

Need to add a post-install check for cuda libraries because it's not bundled with cupy.

_Originally posted by @mdbenito in https://github.com/appliedAI-Initiative/pyDVL/pull/365#discussion_r1244909462_

**Comment by AnesBenmerzoug** [comment]
Markus did actually add an inverted index for the extras a long time ago but I removed it in [this commit](https://github.com/appliedAI-Initiative/pyDVL/pull/140/commits/a2aaf2ae5808c6ffa105ba765f5fe2dac60e88b3) to simplify things and because we only had one extra requirement.
