### ISSUE TITLE
Remove code duplication

### ISSUE THREAD

**Issue by kosmitive** [appliedAI-Initiative/pyDVL#384]
The pull request https://github.com/appliedAI-Initiative/pyDVL/pull/372/files and pull request https://github.com/appliedAI-Initiative/pyDVL/pull/338 contain code duplication as they both use the sequential executor framework. These need to be unified, but it can't be addressed prior to merging at least on of them to develop.

**Comment by kosmitive** [comment]
Related to #387

**Comment by mdbenito** [comment]
Closing because whatever choice is made in #387 will inevitably lead to rewriting and unification of duplicated code
