### ISSUE TITLE
Add tests' documentation to rendered docs

### ISSUE THREAD

**Issue by kosmitive** [appliedAI-Initiative/pyDVL#386]
We added complex derivations to the tests. It would be beneficial to add docstrings of tests to the API reference inside of the documentation. Without it it is very hard to read the latex in code. Or we add the derivation inside of the documentation itself and not the docstring of the test. Thoughts?

**Comment by mdbenito** [comment]
Rendering docs for all tests would severely pollute the documentation. Do you have any specific examples in mind?

**Comment by mdbenito** [comment]
After giving this some thought I think the complex derivations could / should be moved to the main documentation if they belong there, or be left in the tests. Either they pertain to the use of the library or they don't... => closing
