### ISSUE TITLE
Return simple types from HVP solvers

### ISSUE THREAD

**Issue by mdbenito** [appliedAI-Initiative/pyDVL#390]
b52ef72ce7f5b0fc8da12100f211886f563add4d introduces `iHVPResult`, which makes it a bit awkward. We should return a value that behaves as such, e.g. by subclassing Tensor and adding a status dic.

**Comment by Xuzzo** [comment]
Closing. See comment https://github.com/appliedAI-Initiative/pyDVL/pull/376#issuecomment-1665401857
