### ISSUE TITLE
Interactive notebooks on Binder and/or Google Colab

### ISSUE THREAD

**Issue by AnesBenmerzoug** [appliedAI-Initiative/pyDVL#74]
In order to make it easier for people to play around with the library it would be nice to create interactive notebooks with [binder](https://mybinder.org/) and/or [google colab](https://colab.research.google.com/).

This can of course only be done after the repository has been made publicly available. 

- [x] Add Binder links
- [ ] Add Colab links

**Comment by mdbenito** [comment]
Closed with #142. We can think of adding / switching to colab some other time
